package com.programmerfriend.unsplash.usecases.gateways

import com.programmerfriend.unsplash.usecases.images.GetAllImagesUseCase

interface UnsplashRepository : GetAllImagesUseCase.UnsplashImageRepository