package com.programmerfriend.unsplash.usecases.gateways

import com.programmerfriend.unsplash.usecases.images.GetNewImagesUseCase

interface UnsplashRepository : GetNewImagesUseCase.UnsplashImageRepository